[package]
name = "xnet-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
xnet-common = { path = "../xnet-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "xnet"
path = "src/main.rs"
